// eslint-disable-next-line import/prefer-default-export
export enum NOTIFICATION_TYPES {
    SALE_DOWN = 'SALE_DOWN',
    SALE_DOWN_APROVED = 'SALE DOWN APROVED',
    PREBILL_APROVED_REQUESTED = 'PREBILL_APROVED_REQUESTED',
    PREBILL_STATUS_CHANGED = 'PREBILL_STATUS_CHANGED',
    LEAD_REASSIGNED = 'LEAD_REASSIGNED',
    LEAD_TO_REASSIGN = 'LEAD_TO_REASSIGN',
    CREDIT_APPLICATION= 'CREDIT_APPLICATION',
    RESPONSE_CREDIT_APPLICATION = 'RESPONSE_CREDIT_APPLICATION',
    WALLET_APROVED_REQUESTED = 'WALLET_APROVED_REQUESTED',
    WALLET_APROVED_REQUESTED_LEAD = 'WALLET_APROVED_REQUESTED_LEAD',
    WALLET_CONFIRM_DOCUMENTS = 'WALLET_CONFIRM_DOCUMENTS',
    WALLET_STATUS_CHANGED = 'WALLET_STATUS_CHANGED',
    BOSS_MESSAGE = 'BOSS_MESSAGE',
    QUOTERESERVEVALUE='QUOTERESERVEVALUE',
    SALE_DOWN_CALL_CENTER = 'SALE_DOWN_CALL_CENTER',
    NEW_TRACING = 'NEW_TRACING',
    PUBLIC_CATALOG = 'PUBLIC_CATALOG',

}
